#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AG_Mobile.Resource", IsApplication=true)]

namespace AG_Mobile
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::AG_Mobile.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int activity_horizontal_margin = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int activity_vertical_margin = 2130837505;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int ic_dashboard_black_24dp = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int ic_home_black_24dp = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int ic_notifications_black_24dp = 2130903042;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int applicationTab = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int btnLogin = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int btnRegister = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int container = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int form = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int gridLayout1 = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int lblName = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int lblPassword = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int lblPasswordC = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int lblStudentNo = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int lblSurname = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int lblUsername = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int lnkRegister = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int loginContainer = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int loginTab = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int logoutTab = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int navigation = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int navigation_dashboard = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int navigation_home = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int navigation_notifications = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int profileTab = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int registerContainer = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int txtName = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int txtPassword = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int txtPasswordC = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int txtStudentNo = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int txtSurname = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int txtUsername = 2130968603;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int activity_main = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int login = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int register = 2131034114;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F060000
			public const int navigation = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F070000
			public const int ic_launcher = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int ic_launcher_foreground = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int ic_launcher_round = 2131165186;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int app_name = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int base_url = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int title_dashboard = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int title_home = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int title_notifications = 2131230724;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int AppTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0A0000
			public const int xamarin_essentials_fileprovider_file_paths = 2131361792;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
